export * from "./ICart.interface"
export * from "./IUser.interface"
export * from "./IProducts.interface"
export * from "./IImage.interface"
export * from "./ICompany.interface"
export * from "./IProduct-categories.interface"